dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install: travis_retry composer install --no-interaction

script: ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Test
      env: COVERAGE_ENABLED=1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
        - mkdir -p build/logs
        - mkdir -p build/coverage
      script:
        - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      after_script:
        - ./vendor/bin/coveralls  -v

    - stage: Code-style
      script:
        - ./vendor/bin/phpcs

notifications:
  email:
      - swansoft_team@groups.163.com
