language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
      - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
    - mkdir -p build/logs
    - mkdir -p build/coverage
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - if [ -f build/logs/clover.xml ]; then ./vendor/bin/coveralls  -v; fi;

notifications:
  email:
      - swansoft_team@groups.163.com
