language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
      - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
    - mkdir -p build/logs
    - mkdir -p build/coverage
    - ./tests/run-tests.php -c ../build/logs/clover. all

after_script:
    - php vendor/bin/coveralls  -v

notifications:
  email:
      - swansoft_team@groups.163.com
